# Generated by Django 4.1.1 on 2022-09-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(choices=[('new', 'danger'), ('bestseller', 'primary'), ('sale', 'warning')], max_length=10)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category', models.CharField(choices=[('S', 'Shrit'), ('SW', 'Sport wears'), ('OW', 'Outwears')], max_length=2)),
                ('image', models.ImageField(upload_to='clothing_pics')),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=1)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_on', '-added_on'],
            },
        ),
    ]
