# Generated by Django 4.1.1 on 2022-09-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('danger', 'new'), ('primary', 'bestseller'), ('warning', 'sale')], max_length=10, null=True),
        ),
    ]
