# Generated by Django 4.1.1 on 2022-09-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wears'), ('OW', 'Outwears')], max_length=2),
        ),
    ]
