# Generated by Django 4.1.1 on 2022-09-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('sportwear', 'Sport wear'), ('outwear', 'Outwear')], max_length=10),
        ),
    ]
