# Generated by Django 4.1.1 on 2022-09-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
    ]
