# Generated by Django 4.1.1 on 2022-09-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_orderitem_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='customer',
            new_name='user',
        ),
    ]
